SNOWFLAKE_ACCOUNT      = "cnhbzxy-gp38779"
SNOWFLAKE_USER         = "VUDAN"
SNOWFLAKE_PASSWORD     = "1"
SNOWFLAKE_ROLE         = "DATA_ANALYST"
SNOWFLAKE_WAREHOUSE    = "COMPUTE_WH"
SNOWFLAKE_DATABASE     = "BIGDATA_DB"
SNOWFLAKE_SCHEMA       = "STAGING"